name: Generate Profile Animations

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=%231d4ed8&color_dots=%23dbeafe,%2393c5fd,%2360a5fa,%232563eb,%231e3a8a
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%2360a5fa&color_dots=%230f172a,%231e293b,%23334155,%233b82f6,%23bfdbfe

      - name: Deploy snake animation to output branch
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
